-- OpenTTD-Web Grundschema (Phase 1)
CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT NOT NULL UNIQUE,
	pw_hash TEXT NOT NULL,
	created_at INTEGER NOT NULL,
	verified_at INTEGER
);

CREATE TABLE IF NOT EXISTS sessions (
	id TEXT PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	expires_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS settings (
	user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
	json TEXT NOT NULL DEFAULT '{}',
	updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS saves (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	slot INTEGER NOT NULL,
	name TEXT NOT NULL DEFAULT '',
	size INTEGER NOT NULL DEFAULT 0,
	r2_key TEXT NOT NULL,
	updated_at INTEGER NOT NULL,
	UNIQUE(user_id, slot)
);

CREATE TABLE IF NOT EXISTS entitlements (
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	feature TEXT NOT NULL,
	granted_at INTEGER NOT NULL,
	source TEXT NOT NULL DEFAULT 'manual',
	PRIMARY KEY (user_id, feature)
);
